project:
  type: website

website:
  title: "Likelihood Log"
  site-url: "https://likelihood-log.com"
  navbar:
    left:
      - text: Home
        href: index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



